### ISSUE TITLE
pip install on OSX not working

### ISSUE THREAD

**Issue by acow888** [sci-visus/OpenVisus#62]
I am using python 3.7.3 (installed with homebrew) on Mojave 10.14.4.

Installing numpy and OpenVisus via pip with the following command completes successfully:
`python3 -m pip install --user numpy OpenVisus`

 However trying to create the scripts fails, i.e.:
`python3 -m OpenVisus CreateScripts`

Below is the resulting error:
```
Traceback (most recent call last):
  File "/Users/adam/Library/Python/3.7/lib/python/site-packages/OpenVisus/./VisusKernelPy.py", line 29, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: dlopen(/Users/adam/Library/Python/3.7/lib/python/site-packages/OpenVisus/bin/_VisusKernelPy.so, 2): Library not loaded: /Users/travis/build/sci-visus/OpenVisus/build/RelWithDebInfo/site-packages/OpenVisus/bin/libVisusKernel.dylib
  Referenced from: /Users/adam/Library/Python/3.7/lib/python/site-packages/OpenVisus/bin/_VisusKernelPy.so
  Reason: image not found
...
```

It appears that it is trying to reference `libVisusKernel.dylib` from the travis build rather than the install location, because that library does exist in my install directory at:
```
/Users/adam/Library/Python/3.7/lib/python/site-packages/OpenVisus/bin/libVisusKernel.dylib
```

**Comment by spetruzza** [comment]
Thank you Adam, can you try using the latest version to see if the issue is fixed? Just do (as from the latest README):
`
python3 -m pip uninstall OpenVisus
python3 -m pip install --user numpy OpenVisus
python3 -m OpenVisus configure 
`

**Comment by acow888** [comment]
This seems to fix the issue. I am able to open the viewer and run the test scripts successfully now.  Thank you!
